---
title: "Rotten Tomatoes"
author: "Emily Schrader and Katie Voegele"
date: "5/15/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(rvest)
```


Our Hypothesis


```{r saving urls, include=FALSE}
movies2018 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2018")
movies2017 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2017")
movies2016 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2016")
movies2015 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2015")
movies2014 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2014")
movies2013 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2013")
movies2012 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2012")
movies2011 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2011")
movies2010 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2010")
movies2009 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2009")
movies2009 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2009")
movies2008 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2008")
movies2007 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2007")
movies2006 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2006")
movies2005 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2005")
movies2004 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2004")
movies2003 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2003")
movies2002 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2002")
movies2001 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2001")
movies2000 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=2000")
movies1999 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=1999")
movies1998 <- read_html("https://www.rottentomatoes.com/top/bestofrt/?year=1998")
```

```{r url to nodes, include= FALSE}
title2018 <- html_nodes(movies2018, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2018)") %>%
  str_trim()
score2018 <- html_nodes(movies2018, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+") %>%
  parse_double()
title2017 <- html_nodes(movies2017, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2017)")%>%
  str_trim()
score2017 <- html_nodes(movies2017, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2016 <- html_nodes(movies2016, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2016)")%>%
  str_trim()
score2016 <- html_nodes(movies2016, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2015 <- html_nodes(movies2015, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2015)")%>%
  str_trim()
score2015 <- html_nodes(movies2015, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2014 <- html_nodes(movies2014, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2014)")%>%
  str_trim()
score2014 <- html_nodes(movies2014, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2013 <- html_nodes(movies2013, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2013)")%>%
  str_trim()
score2013 <- html_nodes(movies2013, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2012 <- html_nodes(movies2012, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2012)")%>%
  str_trim()
score2012 <- html_nodes(movies2012, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2011 <- html_nodes(movies2011, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2011)")%>%
  str_trim()
score2011 <- html_nodes(movies2011, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2010 <- html_nodes(movies2010, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2010)")%>%
  str_trim()
score2010 <- html_nodes(movies2010, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2009 <- html_nodes(movies2009, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2009)")%>%
  str_trim()
score2009 <- html_nodes(movies2009, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2008 <- html_nodes(movies2008, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2008)")%>%
  str_trim()
score2008 <- html_nodes(movies2008, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2007 <- html_nodes(movies2007, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2007)")%>%
  str_trim()
score2007 <- html_nodes(movies2007, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2006 <- html_nodes(movies2006, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2006)")%>%
  str_trim()
score2006 <- html_nodes(movies2006, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2005 <- html_nodes(movies2005, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2005)")%>%
  str_trim()
score2005 <- html_nodes(movies2005, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2004 <- html_nodes(movies2004, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2004)")%>%
  str_trim()
score2004 <- html_nodes(movies2004, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2003 <- html_nodes(movies2003, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2003)")%>%
  str_trim()
score2003 <- html_nodes(movies2003, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2002 <- html_nodes(movies2002, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2002)")%>%
  str_trim()
score2002 <- html_nodes(movies2002, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2001 <- html_nodes(movies2001, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2001)")%>%
  str_trim()
score2001 <- html_nodes(movies2001, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title2000 <- html_nodes(movies2000, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(2000)")%>%
  str_trim()
score2000 <- html_nodes(movies2000, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title1999 <- html_nodes(movies1999, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(1999)")%>%
  str_trim()
score1999 <- html_nodes(movies1999, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
title1998 <- html_nodes(movies1998, "#top_movies_main .articleLink")%>%
  str_extract("  (.*)(1998)")%>%
  str_trim()
score1998 <- html_nodes(movies1998, "#top_movies_main .tMeterScore")%>%
  str_extract("[1,2,3,4,5,6,7,8,9,0]+")%>%
  parse_double()
```

Began by scraping data from Rotten Tomatoes 

```{r review numbers, include = FALSE}
review_num2018 <- html_nodes(movies2018, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2017 <- html_nodes(movies2017, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2016 <- html_nodes(movies2016, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2015 <- html_nodes(movies2015, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2014 <- html_nodes(movies2014, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2013 <- html_nodes(movies2013, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2012 <- html_nodes(movies2012, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2011 <- html_nodes(movies2011, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2010 <- html_nodes(movies2010, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2009 <- html_nodes(movies2009, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2008 <- html_nodes(movies2008, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2007 <- html_nodes(movies2007, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2006 <- html_nodes(movies2006, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2005 <- html_nodes(movies2005, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2004 <- html_nodes(movies2004, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2003 <- html_nodes(movies2003, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2002 <- html_nodes(movies2002, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2001 <- html_nodes(movies2001, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num2000 <- html_nodes(movies2000, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num1999 <- html_nodes(movies1999, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
review_num1998 <- html_nodes(movies1998, "td.hidden-xs")%>%
  str_extract("[1234567890]+")%>%
  parse_double()
```

```{r strings to tibbles, include= FALSE}
tib2018 <- tibble(title2018, score2018, review_num2018) %>%
  mutate(
    Year = str_extract(title2018, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2018,
    Score = score2018,
    Review_num = review_num2018
  )
tib2017 <- tibble(title2017, score2017, review_num2017) %>%
  mutate(
    Year = str_extract(title2017, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2017,
    Score = score2017,
    Review_num = review_num2017
  )
tib2016 <- tibble(title2016, score2016, review_num2016) %>%
  mutate(
    Year = str_extract(title2016, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2016,
    Score = score2016,
    Review_num = review_num2016
  )
tib2015 <- tibble(title2015, score2015, review_num2015) %>%
  mutate(
    Year = str_extract(title2015, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2015,
    Score = score2015,
    Review_num = review_num2015
  )
tib2014 <- tibble(title2014, score2014, review_num2014) %>%
  mutate(
    Year = str_extract(title2014, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2014,
    Score = score2014,
    Review_num = review_num2014
  )
tib2013 <- tibble(title2013, score2013, review_num2013) %>%
  mutate(
    Year = str_extract(title2013, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2013,
    Score = score2013,
    Review_num = review_num2013
  )
tib2012 <- tibble(title2012, score2012, review_num2012) %>%
  mutate(
    Year = str_extract(title2012, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2012,
    Score = score2012,
    Review_num = review_num2012
  )
tib2011 <- tibble(title2011, score2011, review_num2011) %>%
  mutate(
    Year = str_extract(title2011, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2011,
    Score = score2011,
    Review_num = review_num2011
  )
tib2010 <- tibble(title2010, score2010, review_num2010) %>%
  mutate(
    Year = str_extract(title2010, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2010,
    Score = score2010,
    Review_num = review_num2010
  )
tib2009 <- tibble(title2009, score2009, review_num2009) %>%
  mutate(
    Year = str_extract(title2009, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2009,
    Score = score2009,
    Review_num = review_num2009
  )
tib2008 <- tibble(title2008, score2008, review_num2008) %>%
  mutate(
    Year = str_extract(title2008, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2008,
    Score = score2008,
    Review_num = review_num2008
  )
tib2007 <- tibble(title2007, score2007, review_num2007)%>%
  mutate(
    Year = str_extract(title2007, "[1,2,3,4,5,6,7,8,9,0]{4}$")) %>%
  rename(
    Title = title2007,
    Score = score2007,
    Review_num = review_num2007
  )
tib2006 <- tibble(title2006, score2006, review_num2006)%>%
  mutate(
    Year = str_extract(title2006, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title2006,
    Score = score2006,
    Review_num = review_num2006
  )
tib2005 <- tibble(title2005, score2005, review_num2005)%>%
  mutate(
    Year = str_extract(title2005, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title2005,
    Score = score2005,
    Review_num = review_num2005
  )
tib2004 <- tibble(title2004, score2004, review_num2004)%>%
  mutate(
    Year = str_extract(title2004, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title2004,
    Score = score2004,
    Review_num = review_num2004
  )
tib2003 <- tibble(title2003, score2003, review_num2003)%>%
  mutate(
    Year = str_extract(title2003, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title2003,
    Score = score2003,
    Review_num = review_num2003
  )
tib2002 <- tibble(title2002, score2002, review_num2002)%>%
  mutate(
    Year = str_extract(title2002, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title2002,
    Score = score2002,
    Review_num = review_num2002
  )
tib2001 <- tibble(title2001, score2001, review_num2001)%>%
  mutate(
    Year = str_extract(title2001, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title2001,
    Score = score2001,
    Review_num = review_num2001
  )
tib2000 <- tibble(title2000, score2000, review_num2000)%>%
  mutate(
    Year = str_extract(title2000, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title2000,
    Score = score2000,
    Review_num = review_num2000
  )
tib1999 <- tibble(title1999, score1999, review_num1999)%>%
  mutate(
    Year = str_extract(title1999, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title1999,
    Score = score1999,
    Review_num = review_num1999
  )
tib1998 <- tibble(title1998, score1998, review_num1998)%>%
  mutate(
    Year = str_extract(title1998, "[1,2,3,4,5,6,7,8,9,0]{4}$"))%>%
  rename(
    Title = title1998,
    Score = score1998,
    Review_num = review_num1998
  )

Popular_movies <- tib2018 %>%
  full_join(tib2017) %>%
  full_join(tib2016) %>%
  full_join(tib2015) %>%
  full_join(tib2014) %>%
  full_join(tib2013) %>%
  full_join(tib2012) %>%
  full_join(tib2011) %>%
  full_join(tib2010) %>%
  full_join(tib2009) %>%
  full_join(tib2008) %>%
  full_join(tib2007) %>%
  full_join(tib2006) %>%
  full_join(tib2005) %>%
  full_join(tib2004) %>%
  full_join(tib2003) %>%
  full_join(tib2002) %>%
  full_join(tib2001) %>%
  full_join(tib2000) %>%
  full_join(tib1999) %>%
  full_join(tib1998)
```


```{r, audience scores, include = FALSE}

audienceScore2017 <- tibble(
Title = c("Lady Bird (2017","Get Out (2017","Dunkirk (2017","Coco (2017","The Big Sick (2017","Wonder Woman (2017","Logan (2017","Star Wars: The Last Jedi (2017","The Shape of Water (2017","The Florida Project (2017","Baby Driver (2017","Thor: Ragnarok (2017","Three Billboards Outside Ebbing, Missouri (2017","War for the Planet of the Apes (2017","Spider-Man: Homecoming (2017","I Am Not Your Negro (2017","Hidden Figures (2017","Logan Lucky (2017","The Salesman (Forushande) (2017","The Disaster Artist (2017"), Audience_Review = c(79, 86, 81, 94, 88, 88, 90, 47, 74, 79, 86, 87, 86, 84, 88, 84, 93,75, 83, 87), Year = 2017)


audienceScore1998 <- tibble(Title = c("The Truman Show (1998", "Antz (1998", "Shakespeare in Love (1998", "Saving Private Ryan (1998", "Gods and Monsters (1998", "Out of Sight (1998", "A Bug's Life (1998", "Central Station (Central do Brasil) (1998", "The Dreamlife of Angels (1998", "Rushmore (1998", "Ever After: A Cinderella Story (1998", "A Simple Plan (1998", "Cure (1998", "One True Thing (1998", "The Apostle (1998", "Pleasantville (1998", "Mulan (1998", "Pi (1998", "Hilary and Jackie (1998", "The Parent Trap (1998"), Audience_Review = c(88,52,80,95,83,74,72,95,83,91,84,81,83,71,78,79,85,85,83,70), Year = 1998)

audienceScores <- full_join(audienceScore2017, audienceScore1998) 
ScoreCompare <- Popular_movies %>%
  type_convert()%>%
  inner_join(audienceScores)



```


```{r Using the tibble, include= FALSE, eval = FALSE} 
Popular_movies %>%
  group_by(Year) %>%
  mutate(
    AverageScore = mean(Score)
  ) %>%
  ungroup() %>%
  type_convert() %>%
  ggplot(aes(x = Year, label = Title)) +
  geom_point(aes(y = Score)) +
  geom_line(aes(y = AverageScore)) +
  geom_text(data=subset(Popular_movies, Score > 99 ), aes(y = Score), 
              check_overlap = TRUE, size = 2.5, nudge_y = 1)

#The line and point that works
Popular_movies %>%
  filter( Year != 2018) %>%
  group_by(Year) %>%
  mutate(
    AverageScore = mean(Score)
  ) %>%
  ungroup() %>%
  type_convert() %>%
  ggplot(aes(x = Year)) +
  geom_jitter(aes(y = Score),width = 0.08, alpha = .3) +
  geom_line(aes(y = AverageScore), color = "maroon") 

#Just line
Popular_movies %>%
  group_by(Year) %>%
  summarize(
    AverageScore = mean(Score)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  filter( Year != 2018)%>%
  ggplot(aes(x = Year)) +
  geom_line(aes(y = AverageScore))

#Range of scores overall
Popular_movies %>%
  filter( Year != 2018) %>%
  ggplot(aes( x = Score)) +
  geom_histogram(bins = 33) 

#Figuring out issues
Popular_movies %>%
  filter( Review_num == 0)

#Review dist
Popular_movies %>%
  filter(Year!=2018) %>%
  group_by(Year) %>%
  mutate(
    AverageReviewers = mean(Review_num),
    AverageScore = mean(Score)
  ) %>%
  ungroup() %>%
  type_convert() %>%
  ggplot( aes(x = Year)) +
  geom_jitter(aes( y = Review_num, color = AverageScore), width = .1, alpha = .3) +
  geom_line(aes( y = AverageReviewers), color = "maroon")

Popular_movies %>%
  filter(Year != 2018)%>%
  group_by(Year)%>%
  mutate(Score, 
         Range = max(Score)-min(Score))%>%
  type_convert() %>%
  ungroup() %>%
  ggplot(mapping = aes(x = Year, y = Range))+
  geom_line()


#List of 

#Combined Line plot
Popular_movies %>%
  group_by(Year) %>%
   mutate(
    AverageReviewers = mean(Review_num),
    AverageScore = mean(Score)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  filter( Year != 2018)%>%
  ggplot(aes(x = Year)) +
  geom_line(aes(y = AverageScore), color = "maroon") +
  geom_line(aes(y = AverageReviewers), color = "navy")

rescale01 <- function(x) {
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1]) }

#Combined plots
Popular_movies %>%
  group_by(Year) %>%
   mutate(
    AverageReviewers = mean(Review_num),
    AverageScore = mean(Score)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  filter( Year != 2018)%>%
  ggplot(aes(x = Year)) +
  geom_jitter(aes(y = Score),width = 0.08, alpha = .3, color = "red") +
  geom_line(aes(y = AverageScore), color = "maroon") +
  geom_jitter(aes( y = Review_num), width = .1, alpha = .3, color = "blue") +
  geom_line(aes(y = AverageReviewers), color = "navy") 


#Combined plots rescaled
Popular_movies %>%
  mutate(
    AdjustedReviewers = ((rescale01(Review_num))*100)
  ) %>%
  group_by(Year) %>%
   mutate(
    AverageReviewers = mean(AdjustedReviewers),
    AverageScore = mean(Score)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  filter( Year != 2018)%>%
  ggplot(aes(x = Year)) +
  geom_jitter(aes(y = Score),width = 0.08, alpha = .3, color = "red") +
  geom_line(aes(y = AverageScore), color = "maroon") +
  geom_jitter(aes( y = AdjustedReviewers), width = .1, alpha = .3, color = "blue") +
  geom_line(aes(y = AverageReviewers), color = "navy") 


#Combined plots, both scaled
Popular_movies %>%
  mutate(
    AdjustedReviewers = ((rescale01(Review_num))),
    AdjustedScore = ((rescale01(Score)))
  ) %>%
  group_by(Year) %>%
   mutate(
    AverageReviewers = mean(AdjustedReviewers),
    AverageScore = mean(AdjustedScore)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  filter( Year != 2018)%>%
  ggplot(aes(x = Year)) +
  geom_jitter(aes(y = AdjustedScore),width = 0.08, alpha = .3, color = "red") +
  geom_line(aes(y = AverageScore), color = "maroon") +
  geom_jitter(aes( y = AdjustedReviewers), width = .1, alpha = .3, color = "blue") +
  geom_line(aes(y = AverageReviewers), color = "navy") 

#Combined, new method
Popular_movies %>%
  filter( Year != 2018) %>%
  group_by(Year) %>%
   mutate(
    AverageReviewers = mean(Review_num),
    AverageScore = mean(Score)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  gather(Score, Review_num , key= "Key", value = "Number") %>%
  ggplot(aes(x = Year, color = Key)) +
  geom_jitter(aes(y = Number), alpha = .3, width = .08) +
  geom_line(aes( y = AverageScore), color = "navy") +
  geom_line(aes( y = AverageReviewers), color = "maroon")

#Smooth Instead?
Popular_movies %>%
  filter( Year != 2018) %>%
  group_by(Year) %>%
   mutate(
    AverageReviewers = mean(Review_num),
    AverageScore = mean(Score)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  gather(Score, Review_num , key= "Key", value = "Number") %>%
  ggplot(aes(x = Year, y = Number, color = Key)) +
  geom_jitter(alpha = .3, width = .08) +
  geom_smooth()
  


Popular_movies %>%
  filter( Year != 2018) %>%
  mutate(Year = fct_collapse(Year,
                                "1998 to 2000" = c("1998", "1999", "2000"),
                                "2001 to 2003" = c("2001", "2002", "2003"),
                                "2004 to 2006" = c("2004", "2005", "2006"),
                                "2007 to 2009" = c("2007", "2008", "2009"),
                                "2010 to 2012" = c("2010", "2011", "2012"),
                                "2013 to 2015" = c("2013", "2014", "2015"),
                                "2016 to 2017" = c("2016", "2017")
  )) %>%
  ggplot(aes( x = Score)) +
  geom_density(aes( color = Year)) 


#audience score comparisons
ScoreCompare %>%
  gather(Score, Audience_Review, key = "Reviewer", value = Score) %>%
  mutate( Reviewer = fct_recode(Reviewer,
             "Critics" = "Score",
             "Audience" = "Audience_Review")) %>%
  ggplot(aes(x = as.character(Year), y = Score, color = Reviewer)) +
  geom_jitter(alpha = .7, width = .08) +
  xlab("Year") +
  ggtitle("Audience and Critics Reviews for the Top 20 movies in 1998 and 2017")

ScoreCompare %>%
  gather(Score, Audience_Review, key = "Reviewer", value = Score) %>%
  mutate( Reviewer = fct_recode(Reviewer,
             "Critics" = "Score",
             "Audience" = "Audience_Review")) %>%
  ggplot(aes(x = Reviewer, y = Score)) +
  geom_boxplot() +
  ggtitle("Scores for the Top 20 Movies in 1998 and 2017")

```


```{r, our beautiful graphs, echo= FALSE, warning= FALSE}

rescale01 <- function(x) {
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1]) }

Popular_movies %>%
  filter( Year != 2018) %>%
  group_by(Year) %>%
  mutate(
    AverageScore = mean(Score)
  ) %>%
  ungroup() %>%
  type_convert() %>%
  ggplot(aes(x = Year)) +
  geom_jitter(aes(y = Score),width = 0.08, alpha = .3) +
  geom_line(aes(y = AverageScore), color = "maroon") +
  ggtitle("Critic Scores by Year")
#Graph of movies by year plain

Popular_movies %>%
  filter( Year != 2018) %>%
  ggplot(aes( x = Score)) +
  geom_histogram(aes( fill = Year), bins = 33)+
  ggtitle("Distribution of Critic Scores")
#Shows the distribution 

Popular_movies %>%
  filter( Year != 2018) %>%
  mutate(Year = fct_collapse(Year,
                                "1998 to 2000" = c("1998", "1999", "2000"),
                                "2001 to 2003" = c("2001", "2002", "2003"),
                                "2004 to 2006" = c("2004", "2005", "2006"),
                                "2007 to 2009" = c("2007", "2008", "2009"),
                                "2010 to 2012" = c("2010", "2011", "2012"),
                                "2013 to 2015" = c("2013", "2014", "2015"),
                                "2016 to 2017" = c("2016", "2017")
  )) %>%
  ggplot(aes( x = Score)) +
  geom_density(aes( color = Year)) +
  ggtitle("Density Plot of Critic Scores by Year")
#Density plot showing the distribution for each group of 2-3 years


Popular_movies %>%
  filter( Year != 2018) %>%
  mutate(Year = fct_collapse(Year,
                                "1998 to 2000" = c("1998", "1999", "2000"),
                                "2001 to 2003" = c("2001", "2002", "2003"),
                                "2004 to 2006" = c("2004", "2005", "2006"),
                                "2007 to 2009" = c("2007", "2008", "2009"),
                                "2010 to 2012" = c("2010", "2011", "2012"),
                                "2013 to 2015" = c("2013", "2014", "2015"),
                                "2016 to 2017" = c("2016", "2017")
  )) %>%
  ggplot(aes( x = Review_num)) +
  geom_density(aes( color = Year))+
  ggtitle("Number of Reviewers by Year")
#Reviewer density plot

Popular_movies %>%
  filter( Year != 2018) %>%
  group_by(Year) %>%
  mutate(
    AverageReviews = mean(Review_num)
  ) %>%
  ungroup() %>%
  type_convert() %>%
  ggplot(aes(x = Year)) +
  geom_jitter(aes(y = Review_num),width = 0.08, alpha = .3) +
  geom_line(aes(y = AverageReviews), color = "navy") +
  ggtitle("Number of Reviewers by Year")


Popular_movies %>%
  group_by(Year) %>%
   mutate(
    AverageReviewers = mean(Review_num),
    AverageScore = mean(Score)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  filter( Year != 2018)%>%
  ggplot(aes(x = Year)) +
  geom_line(aes(y = AverageScore), color = "maroon") +
  geom_line(aes(y = AverageReviewers), color = "navy")+
  ggtitle("Scores and Review Numbers by Year")
#Line plot comparing Reviews (Navy) and Scores (maroon)


Popular_movies %>%
  mutate(
    AdjustedReviewers = ((rescale01(Review_num))*100)
  ) %>%
  group_by(Year) %>%
   mutate(
    AverageReviewers = mean(AdjustedReviewers),
    AverageScore = mean(Score)
  ) %>%
  type_convert() %>%
  ungroup() %>%
  filter( Year != 2018)%>%
  ggplot(aes(x = Year)) +
  geom_jitter(aes(y = Score),width = 0.08, alpha = .3, color = "red") +
  geom_line(aes(y = AverageScore), color = "maroon") +
  geom_jitter(aes( y = AdjustedReviewers), width = .1, alpha = .3, color = "blue") +
  geom_line(aes(y = AverageReviewers), color = "navy")+
  ggtitle("Scores and Review Numbers by Year")
#shows the relationship between Review numbers (blue) and Scores (red)


Popular_movies%>%
  filter(Year != 2018, Score == 100) %>%
  arrange(desc(Year), desc(Review_num)) %>%
  print(length = Inf)


ScoreCompare %>%
  gather(Score, Audience_Review, key = "Reviewer", value = Score) %>%
  mutate( Reviewer = fct_recode(Reviewer,
             "Critics" = "Score",
             "Audience" = "Audience_Review")) %>%
  ggplot(aes(x = as.character(Year), y = Score, color = Reviewer)) +
  geom_jitter(alpha = .7, width = .08) +
  xlab("Year") +
  ggtitle("Audience and Critics Reviews for the Top 20 movies in 1998 and 2017")
#Point plot showing differences between audience and critics


ScoreCompare %>%
  gather(Score, Audience_Review, key = "Reviewer", value = Score) %>%
  mutate( Reviewer = fct_recode(Reviewer,
             "Critics" = "Score",
             "Audience" = "Audience_Review")) %>%
  ggplot(aes(x = Reviewer, y = Score)) +
  geom_boxplot() +
  ggtitle("Scores for the Top 20 Movies in 1998 and 2017")
#boxplots showing audience and critics

```
